//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alkemy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subjects()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int Subject_Id { get; set; }
        public string Subject_Name { get; set; }
        public System.TimeSpan Subject_StartTime { get; set; }
        public System.TimeSpan Subject_EndingTime { get; set; }
        public string Subject_Day { get; set; }
        public int Subject_Id_Teacher { get; set; }
        public int Subject_Quota { get; set; }
        public Nullable<bool> Subject_State { get; set; }
    
        public virtual Teachers Teachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
